# =====================================
# APPLICATION
# =====================================

spring.application.name=Ecommerce

server.port=8080


# =====================================
# MYSQL DATABASE
# =====================================

spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:21953/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ORlzauQsPiIgYXbyaPRdhUTctNLbwFHE

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# =====================================
# FILE UPLOAD
# =====================================

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB


# =====================================
# GMAIL SMTP (OTP EMAIL)
# =====================================

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# =====================================
# LOGGING
# =====================================

logging.level.org.springframework.web=DEBUG

logging.level.org.hibernate.SQL=DEBUG

# =====================================
# RAZORPAY
# =====================================

razorpay.key.id=rzp_test_T1ZLnmhm72e6h6

razorpay.key.secret=a8ONKjIm57eYRuMsJAZDtvW0
